# 基础设置
title: My Personal Website
description: A simple website made with GitHub Pages & Jekyll
theme: jekyll-theme-cayman

# 页面显示信息
author: Your Name
email: your-email@example.com

# 关闭不需要的功能
show_downloads: false